### ISSUE TITLE
Problems with cocoapods

### ISSUE THREAD

**Issue by diazod** [trywildcard/wildcard_ios_sdk#2]
I am creating  an app in Objective C and I tried implementing your framework with Cocoa Pods, the problem is every time I try to run it,  I get the following error:

dyld: Library not loaded: @rpath/WildcardSDK.framework/WildcardSDK
  Referenced from: /Users/daviddiaz/Library/Developer/CoreSimulator/Devices/9AC4A059-384A-4147-97D5-53A1C23FB8E6/data/Containers/Bundle/Application/AE90C886-19B7-4122-84CF-88D13AD935FD/Dagm8.app/Dagm8
  Reason: image not found

Why you think this happens?

**Comment by zreitano** [comment]
+1! Having this issue, as well! Any help would be much appreciated.

**Comment by DaveX101** [comment]
Hey, the WildcardSDK actually isn't deployed as a Pod right now. I tried to distribute it as a Vendored Framework and opened up a ticket for this issue here https://github.com/CocoaPods/CocoaPods/issues/3281 but it seems it's blocked by something else that hasn't been resolved yet. You can still use the SDK by still doing the installation instructions here (http://www.trywildcard.com/docs/ios-sdk/installing) while still working in your CocoaPod workspace, but just follow all the steps for the Project for your main application (not the Pods project). All the steps still apply and should still work inside the pod workspace. If you're using only Obj C so far make sure to follow the swift specific steps too. Hope it helps

**Comment by zreitano** [comment]
Thanks Dave! That worked!
